### ISSUE TITLE
RuntimeError during run_finetune_lora.sh

### ISSUE THREAD

**Issue by imeursault** [zjunlp/KnowUnDo#1]
I use both `L20` and `RTX 4080` GPU run the `run_finetune_lora.sh` for different models(Llama-2-7B-Chat and Qwen-1.5-7B-Chat)
When running to code line 126: 
```python
# save the model
    if cfg.LoRA.r != 0:
        model = model.merge_and_unload()
```
It shows error:
```bash
Error executing job with overrides: ['model_family=llama2-7b', 'data_type=copyright', 'split=full', 'batch_size=16', 'gradient_accumulation_steps=4', 'lr=3e-4']
Traceback (most recent call last):
  File "/root/xxx/KnowUnDo/pretrain/pretrain.py", line 127, in main
    model = model.merge_and_unload()
  File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 784, in merge_and_unload
    return self._unload_and_optionally_merge(
  File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 438, in _unload_and_optionally_merge
    target.merge(safe_merge=safe_merge, adapter_names=adapter_names)
  File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 415, in merge
    base_layer.weight.data = base_layer.weight.data + delta_weight
RuntimeError: The size of tensor a (0) must match the size of tensor b (4096) at non-singleton dimension 1
```
Also there is an issue in readme's **Environment setup**:
```bash
git clone https://github.com/zjunlp/KnowUnDo.git
cd KnowUnDo
conda create -n KnowUnDo python==3.10

conda activate KnowUnDo
pip install -e .
pip install -r requirements.txt

cd llm_unlearn/apex
pip install -v --no-cache-dir ./
```
The last two commands do not work because git repo do not have this directory.

**Comment by tbozhong** [comment]
Thank you for your attention to our work!

> Error in Finetune

This is a bug in `Peft`. You can directly comment out the code related to `save the model`, as it is not necessary for the subsequent steps, which use adapters to conduct experiments without merging. I have updated the code in the latest release.

> Environment Setup

I also have uploaded the modified version of Apex to the repository. Please try running it again.

If you encounter any issues, feel free to contact us.

**Comment by imeursault** [comment]
Thank you for your help! It seems that there are no problems for now! Thanks for your patience I am very grateful that you could take the time to solve my problem.😄
