### ISSUE TITLE
Issues with saving and loading LoRA weights after pretraining

### ISSUE THREAD

**Issue by piso7** [zjunlp/KnowUnDo#3]
I tried to run the code on both a single A6000 GPU and six A6000 GPUs.

To save the LoRA weights, I uncommented lines 130 and 131, excluding the merging part in lines 126 and 127
```
# save the model
# if cfg.LoRA.r != 0:
#     model = model.merge_and_unload()

model.save_pretrained(cfg.save_dir)
tokenizer.save_pretrained(cfg.save_dir)
```
and ran the finetuning code.
```
# directory: pretrain
bash run_finetune_lora.sh
```
After that, with the saved LoRA weights, I tried to run.
```
bash run_localization.sh
```
And it shows error

```
size mismatch for base_model.model.model.layers.30.mlp.gate_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([11008, 8]).
size mismatch for base_model.model.model.layers.30.mlp.up_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([11008, 8]).
size mismatch for base_model.model.model.layers.30.mlp.down_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([8, 11008])
...
```

To take a closer look, I checked the state_dict of adapter_model.safetensors
```
for key, val in sd.items():
    print(key, val.shape)
```
and here is what I found:
```
base_model.model.model.layers.0.mlp.down_proj.lora_A.weight torch.Size([0])
base_model.model.model.layers.0.mlp.down_proj.lora_B.weight torch.Size([4096, 8])
base_model.model.model.layers.0.mlp.gate_proj.lora_A.weight torch.Size([8, 4096])
base_model.model.model.layers.0.mlp.gate_proj.lora_B.weight torch.Size([0])
base_model.model.model.layers.0.mlp.up_proj.lora_A.weight torch.Size([8, 4096])
base_model.model.model.layers.0.mlp.up_proj.lora_B.weight torch.Size([0])
base_model.model.model.layers.0.self_attn.k_proj.lora_A.weight torch.Size([8, 4096])
base_model.model.model.layers.0.self_attn.k_proj.lora_B.weight torch.Size([4096, 8])
base_model.model.model.layers.0.self_attn.o_proj.lora_A.weight torch.Size([8, 4096])
base_model.model.model.layers.0.self_attn.o_proj.lora_B.weight torch.Size([4096, 8])
base_model.model.model.layers.0.self_attn.q_proj.lora_A.weight torch.Size([8, 4096])
base_model.model.model.layers.0.self_attn.q_proj.lora_B.weight torch.Size([4096, 8])
base_model.model.model.layers.0.self_attn.v_proj.lora_A.weight torch.Size([8, 4096])
base_model.model.model.layers.0.self_attn.v_proj.lora_B.weight torch.Size([4096, 8])
```
The same error occurs in both cases, whether using a single GPU or six GPUs.
Seeing that torch.Size([0]) occurs, I think the LoRA weights were not properly saved after the pre-training.

How can I resolve this error?

**Comment by tbozhong** [comment]
Hi there,

I rerun the pretraining experiment for `copyright` using `Llama-2-7b-chat` and don't encounter any issues. The `state_dict` of my local `adapter_model.safetensors` is as follows:
![image](https://github.com/user-attachments/assets/ba16bd86-4316-4824-8da4-065d32c09106)

You might want to check the version of `peft` you are using. We are using `peft==0.10.0`.

If you have any questions, please feel free to reach out to us.

**Comment by piso7** [comment]
Thank you for helping me check the `state_dict`.

After verifying my PEFT version, I found it matches—`peft==0.10.0`—along with the module versions in the `requirements.txt` are also identical.

After several attempts considering your comment, I found that the issue was indeed related to `deepspeed`.
I am sharing the solution for anyone who might encounter the same issue in the future.
I resolved the problem by modifying the following code at the bottom of `pretrain.py`:
```
    #save the model
    print(f"cfg.LoRA.r: {cfg.LoRA.r}")
    # if cfg.LoRA.r != 0:
    #     model = model.merge_and_unload()
    # model.save_pretrained(cfg.save_dir)
    # tokenizer.save_pretrained(cfg.save_dir)
    import deepspeed

    with deepspeed.zero.GatheredParameters((p for n, p in trainer.model.named_parameters() if "lora" in n)):
        if trainer.accelerator.is_main_process:
            model.save_pretrained(cfg.save_dir)
            tokenizer.save_pretrained(cfg.save_dir)
```

I appreciate your comment and am truly impressed by your insightful research!

**Comment by zxlzr** [comment]
We will update the README file soon. Thank you for your valuable suggestions!
